Eventual\Bundle\Entity\EventCollection:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3

Eventual\Bundle\Entity\Event:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3
        placeName:
            - NotBlank: ~
            - Length:
                min: 3
        description:
            - NotBlank: ~
            - Length:
                min: 5
        date:
            - DateTime: ~
            - GreaterThan:
                value: new \DateTime()
