Eventual\Bundle\Entity\EventCollection:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3

Eventual\Bundle\Entity\Event:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3
        placeName:
            - NotBlank: ~
            - Length:
                min: 3
        coordsLat:
            - Range:
                min: -90
                max: 90
        coordsLong:
            - Range:
                min: -180
                max: 180
        description:
            - NotBlank: ~
            - Length:
                min: 5
        date:
            - DateTime: ~
            - GreaterThan:
                value: new \DateTime()
